services:
  tags:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DISCORD_APP_ID=${DISCORD_APP_ID}
      - DISCORD_PUBLIC_KEY=${DISCORD_PUBLIC_KEY}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - PORT=8020
    networks:
      - caddy
      - tags
    labels:
      caddy_0: tags.b1.buape.com
      caddy_0.reverse_proxy: "{{upstreams 8020}}"

  db:
    environment:
      POSTGRES_DB: tags
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: tags
    ports:
      - 42003:5432
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    networks:
      - tags
    volumes:
    - database:/var/lib/postgresql/data

networks:
  tags:
  caddy:
    external: true

volumes:
  database:
    driver: local
